### ISSUE TITLE
[feature request] german and english audio?

### ISSUE THREAD

**Issue by n00bundercover** [xypwn/southpark-de-downloader#1]
Not sure if possible, but it would be nice to have both audio tracks in one video file.

**Comment by xypwn** [comment]
Unfortunately, you'd have to download the full videos in both languages and can't just download the audio. So yes, technically it would be possible to add the other audio stream with FFMPEG, but at that point you may as well just download it in both languages IMO.

**Comment by xypwn** [comment]
I'm going to close the issue for now since I don't see how this feature could be implemented efficiently. Thanks for the request though and feel free to open a new issue if you know how this could be implemented efficiently.
