### ISSUE TITLE
CLI stopping ALL downloads when an episode can't be downloaded

### ISSUE THREAD

**Issue by Mantarochen01** [xypwn/southpark-de-downloader#10]
Hey, 

first up, great work! I can finally download SP!

Is there the possibility that you can add a flag/parameter to just "skip" failed downloads instead of stopping?

Using the "download all" feature doesn't work that well, if the tool stops downloading entirely when it runs up to an episode that's not available as example!

Greetings, 
Max

**Comment by xypwn** [comment]
Hi Max,

glad you like it!

The script should already automatically skip failed downloads like you're describing. Please provide the full output where it fails so I can reason about why it stopped unexpectedly.

Now although it's not very pretty, when an episode is unavailable it should only give an error but continue downloading. In this case I am downloading S10, with E3+4 unavailable:
`southpark-downloader.sh -s10`:
```
>>> Downloading S10 E3: Cartoon Wars Part I
>>> Possible youtube-dl error! Log:
[southpark.de] Extracting URL: https://www.southpark.de/en/episodes/m6ohvr/south-park-cartoon-wars-part-i-season-10-ep-3
[southpark.de] south-park-cartoon-wars-part-i-season-10-ep-3: Downloading webpage
ERROR: [southpark.de] m6ohvr/south-park-cartoon-wars-part-i-season-10-ep-3: Could not extract mgid; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
>>> End log
>>> Cleaning up temporary files
>>> Downloading S10 E4: Cartoon Wars Part II
>>> Possible youtube-dl error! Log:
[southpark.de] Extracting URL: https://www.southpark.de/en/episodes/ov0kz8/south-park-cartoon-wars-part-ii-season-10-ep-4
[southpark.de] south-park-cartoon-wars-part-ii-season-10-ep-4: Downloading webpage
ERROR: [southpark.de] ov0kz8/south-park-cartoon-wars-part-ii-season-10-ep-4: Could not extract mgid; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
>>> End log
>>> Cleaning up temporary files
>>> Downloading S10 E5: A Million Little Fibers
```

Also, make sure you are using the most recent version!

**Comment by Mantarochen01** [comment]
Hey,

I will add a copy of the CLI output if I can when I get home. On my end the
script just stops when a download fails :(.

Other then that, great tool. This basically just enabled me to rewatch the
entire series over my Plex setup.

Love it :).

xypwn ***@***.***> schrieb am Fr. 28. Juli 2023 um 22:47:

**Comment by Mantarochen01** [comment]
root@ubuntu22-mediavm:~/southpark-de-downloader# ./southpark-downloader.sh -D -s20
Updating episode index
Going to download Season 20
Downloading Season 20 Episode 1 (https://www.southpark.de/folgen/oq0xia/south-park-weisst-du-noch-beeren-staffel-20-ep-1)
possible youtube-dl ERROR
Cleaning up temporary files

This is the standard error I get with the included yt-dlc, no matter what the episode is. 

When I swap the included yt-dlc with a new yt-dlp install, the download works, but it doesnt skip failed downloads.

**Comment by xypwn** [comment]
It seems you're using an older version, since your included downloader is yt-dlc, which I switched out for yt-dlp a while ago. Also, the message indicating a youtube-dl error shows an error log in the most recent version (see the output from my previous comment). If you run `git pull` in the cloned repo, that should update everything.
Let me know if it works!
Also, again, thanks for your positive feedback :). It's really nice to see people getting some worth out of my projects

**Comment by Mantarochen01** [comment]
> If you run `git pull` in the cloned repo, that should update everything.

root@ubuntu22-mediavm:~/southpark-de-downloader# git pull
Already up to date.

THIS: git clone https://git.nobrain.org/r4/southpark-de-downloader.git; cd southpark-de-downloader

is the right REPO tho,right?

**Comment by xypwn** [comment]
Hi, sorry for the late reply. You're right. The repo from the readme you're using is on my old git server, which I haven't updated in a while. I updated the readme now to have the GitHub URL.

Apologies for the misleading readme!

You can try to `git clone https://github.com/xypwn/southpark-de-downloader.git` and everything should work perfectly fine.
