### ISSUE TITLE
Warning "Your region is on , which is currently unknown"

### ISSUE THREAD

**Issue by skr2345** [xypwn/southpark-de-downloader#12]
although I am located in Germany, I get the following:

bash-3.2$ ./southpark-downloader.sh -s 5 -e 13
readlink: illegal option -- f
usage: readlink [-n] [file ...]
\e[33m>>> Your region is on , which is currently unknown. Please open an issue on GitHub. If the program doesn't work, you can try to VPN into Germany.\e[m
\e[32m>>> Updating episode index\e[m
\e[1;31m>>> Unable to find Season 5\e[m

**Comment by xypwn** [comment]
I am also in Germany and it still works for me.

Are you sure you're on the latest GitHub commit?

Also, make sure that you're not connected to a VPN outside of Germany.

Finally, you can check which URL you get redirected to when you go to https://southparkstudios.com/. It should be southpark.de.

**Comment by skr2345** [comment]
it works with yt-dlp flawlessly but with the pretty slow download. The redirection works in browser as well. I have tested it in both High Sierra and Catalina. The UI-version shows in Windows 7 the following error (I hope it will work with the attachment).
![Bildschirmfoto 2023-10-29 um 17 43 03](https://github.com/xypwn/southpark-de-downloader/assets/32097373/3e866357-3a8f-4b59-8309-89d86c8dbf41)

**Comment by xypwn** [comment]
Ahhh I missed the first error message in your initial comment. Readlink is missing the -f option on MacOS. Hopefully I'll be able to get to fixing that tomorrow.

Until then, replacing `readlink -f` by `echo` in the source code might also somewhat help.

Regarding the UI version, the shown error is most likely Windows' fault, since it's a TLS error. Could be for example that the system time isn't set correctly.

Also, the UI version should work for MacOS too, have you tried that?

**Comment by skr2345** [comment]
The UI-versions are not working under MacOS: the app shortly appears in the dock and then closing. The UI-builded version shows the following in the console:
![Bildschirmfoto 2023-10-31 um 10 04 19](https://github.com/xypwn/southpark-de-downloader/assets/32097373/b5419a33-ad39-4727-948f-7ce2f0e76f41)

**Comment by xypwn** [comment]
That's definitely very weird! You should open an issue on the respecive repo for that. I don't really have a lot of time currently, but I'll get to all the problems when I do find the time.

If you want, you can also try to compile the MacOS app app yourself, it should be pretty simple.

**Comment by xypwn** [comment]
Also, the windows issue is probably fixable, as I said.

**Comment by skr2345** [comment]
> That's definitely very weird! You should open an issue on the respecive repo for that. I don't really have a lot of time currently, but I'll get to all the problems when I do find the time.
> 
> If you want, you can also try to compile the MacOS app app yourself, it should be pretty simple.

My message with the attachment of console warning is exactly the compiled MacOS app (mistakenly named as "builded" one).

**Comment by skr2345** [comment]
I have tried the UI version on my PC with Windows 7. It works just fine. Previously I have used the virtual machine with Win7, probably some updates are missed there.
