### ISSUE TITLE
Sadly not working anymore

### ISSUE THREAD

**Issue by Zwackle** [xypwn/southpark-de-downloader#2]
Ahoi! Could you update this so it works on the current website?

**Comment by xypwn** [comment]
I just tested it, works for me. Make sure you are using a German IP address. If the issue persists, maybe try deleting the cache folder. Let me know your results.

**Comment by xypwn** [comment]
I'll close this issue for now since you didn't respond, but feel free to open a new issue if you can reproduce it with a German IP address :)
