### ISSUE TITLE
Downloading but nothing gets stored

### ISSUE THREAD

**Issue by DerElch87** [xypwn/southpark-de-downloader#4]
Hi there,

I tried to download some episodes, but I had no success.
It shows downloading and merging in the end, but there are no videos stored.
Even the cache is always empty - only the episode index gets stored.

I also tried different folders, but no success.

Honestly, I have no idea where to start to find out what happens.

BR
Elch

**Comment by xypwn** [comment]
Your downloads should get stored in the "downloads" folder relative to the cloned repo. You can also change it in config.sh.

If it still doesn't work, you can try inserting the line `echo "Output file: ${OUTFILE}"` after `local OUTFILE="${OUTDIR}/South_Park_S${SEASON_NUMBER}_E${EPISODE_NUMBER}_${OPT_LANG}.mp4"` (southpark-downloader.sh, line 176 on master) to echo where the output file should be to your terminal.

Let me know if it works :)

**Comment by DerElch87** [comment]
Hi xypwn,

I added the lines like you have written above and repeated the same terminal lines like before and what should I say - IT WORKS NOW.

I only thing what could be different is, meanwhile I rebooted the system.
Honestly, I'm looking kind of stupid before, but I'm sure nothing got downloaded.

So in short:
Thank you very much, it works.

**Comment by xypwn** [comment]
Glad I could help :)
