### ISSUE TITLE
Doesn't download anything anymore

### ISSUE THREAD

**Issue by almostserious** [xypwn/southpark-de-downloader#5]
After installing and doing a test run, it actually doesn't download anything anymore.
Is there maybe a new version of Youtube-DL required? Or the site changed its logic?

What happens:
It detects the episode from the index. It tracks the download with 1M. 
However, then it skips the download, & immediately tries to move the file in the downloads folder, but gets an error because there is no .mp4 file

Below is the error message i'm getting:

```
[download] Downloading video 1 of 1
[download] Merging video files
mv: cannot stat './*.mp4': No such file or directory
```

*edit* replacing youtube-dl with yt-dlp actually makes it work again. 
In that case i simply installed yt-dlp via 
`apt install yt-dlp`
Then changed the config.sh youtube-dl path to link to the yt-dlp executable at
` /usr/bin/yt-dlp`

**Comment by xypwn** [comment]
Hey, first of all I apologize for the late response. I now switched the whole repo to yt-dlp, and everything seems to be working again. Thanks for the issue and take care!
