### ISSUE TITLE
Error while running 

### ISSUE THREAD

**Issue by KatzeMau** [xypwn/southpark-de-downloader#8]
On running the Script, I get an Error:
```
 ./southpark-downloader.sh -D -s 12
\e[32m>>> Updating episode index\e[msed: 1: "\@^https://www.southpar ...": unexpected EOF (pending }'s)

\e[1;31m>>> Unable to find Season 12\e[m
```

The setup seamed successful though.

**Comment by xypwn** [comment]
Hi,
it seems like your version of `sed` doesn't support the syntax I used. I need to know which version of set you are using. Please post the output of `sed --version`.

Also, yt-dlp is broken right now, so even if you fix the `sed` issue, I'm afraid you'll have to wait until they fix yt-dlp.

**Comment by KatzeMau** [comment]
@xypwn I just saw the issue in another download project. (https://github.com/yt-dlp/yt-dlp/issues/7037) 
I will watch your repo to get a reminder. 
But otherwise very good work! : )
(I fixed sed)

**Comment by KatzeMau** [comment]
Just a quick other question, do you have discord? I would like to message you something private

**Comment by xypwn** [comment]
Sure, my discord is 自爆猫#3170
