### ISSUE TITLE
yt-dlp broken (I made a new GUI South Park downloader that works)

### ISSUE THREAD

**Issue by xypwn** [xypwn/southpark-de-downloader#9]
MTV borked yt-dlp's extractor. I'll make sure to update the script when they get it working again. I already submitted an issue to yt-dlp: [https://github.com/yt-dlp/yt-dlp/issues/7037](https://github.com/yt-dlp/yt-dlp/issues/7037)

**Comment by xypwn** [comment]
I also recently started a new project: a fully self-contained Desktop/Android GUI app to download SP episodes. Originally, I didn't plan on releasing it so early, but since yt-dlp is broken, I though I'd release it now. Here's the repo: [https://github.com/xypwn/southpark-downloader-ui](https://github.com/xypwn/southpark-downloader-ui)

**Comment by xypwn** [comment]
> I also recently started a new project: a fully self-contained Desktop/Android GUI app to download SP episodes.

Nonetheless, I will still be maintaining this repo, and I will fix this once yt-dlp have resolved their issue.

**Comment by Mantarochen01** [comment]
Hey @xypwn ! Is there a fix for the broken Youtube-dl already? Tried out your UI-tool, but having to klick on all episodes of the 25 seaons by hand + the somewhat "crashyness" are holding me back. Really impressive efforts tho! Tested a bit and the UI version works!

**Comment by xypwn** [comment]
> Hey @xypwn ! Is there a fix for the broken Youtube-dl already? Tried out your UI-tool, but having to klick on all episodes of the 25 seaons by hand + the somewhat "crashyness" are holding me back. Really impressive efforts tho! Tested a bit and the UI version works!

Hi @Mantarochen01, glad the UI somewhat works for you. You're definitely right that it's not exactly the most stable. I tried to make all my code as thread-safe and stable as possible, but it is very well possible I've missed some cases. **If you find a specific bug/crash you can reproduce, please open an issue**. Another problem is the UI toolkit Fyne, which is notorious for race conditions and instability, although I hear they are progressively improving that. I will also add some options in the UI to download more episodes at once.

Regarding the Youtube-dl issue, it seems to have resolved itself. The original problem was that the SP website changed its API, which broke ytdl. It seems though they have reverted that change, meaning the downloader should work again.

**Comment by xypwn** [comment]
So it seems the issue just resolved itself without requiring any modification to youtube-dl.

See https://github.com/yt-dlp/yt-dlp/issues/7037#issuecomment-1656285067 for more info.
